### PR TITLE
Fix html descriptions

### PR DESCRIPTION
**Pull request by koseduhemak**
Fixed invalid html (missing closing tags) in rules description.

### CODE REVIEW

**Comment by koseduhemak** [comment]
@KengoTODA: Would it be possible to take a look at or merge the changes?
We need the description in a proper format as we want to display it inside a html page.

My changes do not cover the whole faulty descriptions yet, but I will continue fixing if I get some response to this issue.

Thank you!

**Review by KengoTODA — COMMENTED** [review]
It is OK to merge this PR, however, these files are [generated](https://github.com/spotbugs/sonar-findbugs/blob/e2b707513a8cbfbb4a026afdfc4cfdbe79def6c5/generate_profiles/README.md) from [message.xml in fb-contrib](https://github.com/mebigfatguy/fb-contrib/blob/spotbugs/etc/messages.xml), so coming release will overwrite this change.

Please consider to submit PR to fb-contrib project too.

**Comment by KengoTODA** [comment]
#336 will update the XML files, so I will merge this PR after we merge #336 to the main branch.

**Comment by koseduhemak** [comment]
Thank you.
I will also try to file a pull request in the source project, so we do not lose the fixes in future versions.

**Comment by KengoTODA** [comment]
Hi @koseduhemak, could you merge `origin/master` to your topic branch, and resolve the conflict?
We updated the `findsecbugs` so XML generated based on it needs to be updated.

**Comment by mrotrebor** [comment]
Hi @KengoTODA . Do you have an estimation when the release with new version will be available? Thanks in advance.

**Review by KengoTODA — APPROVED** [review]

**Pull request merged**
