### PR TITLE
Add back the sonar token

### PR DESCRIPTION
**Pull request by gtoison**

### CODE REVIEW

**Comment by hazendaz** [comment]
Sonar shows not doing this anymore.  However I've not confirmed that is accurate.  Will try this weekend on a separate repo that works.  Believe it's a security reason.

**Comment by gtoison** [comment]
I'm not sure what you're saying, the documentation here https://docs.sonarsource.com/sonarqube-server/latest/analyzing-source-code/scanners/sonarscanner-for-maven/ says to use `-Dsonar.token=myAuthenticationToken`
The Sonar Maven plugin needs the token for authentication

**Comment by hazendaz** [comment]
I can merge but a lot are moving away from that type of setup because it exposes the variable in funny ways although so does the ENV.  My understanding is only the ENV is needed. I removed it after having issues and it clearly doesn't fix anything.  I'll merge it back here.

Separate question, do you know why just this repo isn't showing how many changes are on master in relation to the last release tag?  I poked around but could not see where that is set and releases are being tagged properly.  I did try to tag slightly differently on last release thinking that might help but didn't really do anything.

**Comment by gtoison** [comment]
> Separate question, do you know why just this repo isn't showing how many changes are on master in relation to the last release tag? I poked around but could not see where that is set and releases are being tagged properly. I did try to tag slightly differently on last release thinking that might help but didn't really do anything.

Sorry I don't understand what you're asking: this repo isn't showing changes where exactly? What did you try to tag on the release?

Regarding the sonarcloud analysis, I'm not sure if you are aware but Sonarsource requires that plugins are regularly analysed, so we currently wouldn't be able to release a new version until we get hold of a new token.

**Pull request merged**
