### PR TITLE
Release 3.9 with updated xml

### PR DESCRIPTION
**Pull request by KengoTODA**
This release contains following fixes:

* Bump up SpotBugs to 3.1.8, for better Java 12 support #217 and fixing SpotBugs bugs #212
* SonarQube compatibility 7.4 #218

### CODE REVIEW

**Comment by vboyz** [comment]
LGTM

**Comment by VinodAnandan** [comment]
LGTM

**Comment by KengoTODA** [comment]
Thanks for merging!

I've pushed [3.9.0 tag](https://github.com/spotbugs/sonar-findbugs/releases/tag/3.9.0) to GitHub, and going to deploy artifacts to Maven Central. @VinodAnandan can I ask you to update the release page, and release to SonarQube marketplace?

**Comment by KengoTODA** [comment]
3.9.0 is now on Maven Cental.

http://central.maven.org/maven2/com/github/spotbugs/sonar-findbugs-plugin/3.9.0/

**Comment by VinodAnandan** [comment]
Thank you @KengoTODA. I will do it on Saturday. Hope that's okay?

**Comment by MISSPIKLA** [comment]
> Thank you @KengoTODA. I will do it on Saturday. Hope that's okay?

Hello! Is this new version already on the official Marketplace? I'm not able to locate it and it seems a bit tricky to find that jar file Sonar is talking about on here:
https://docs.sonarqube.org/latest/setup/install-plugin/

**Comment by KengoTODA** [comment]
sorry but I cannot get your point. which part is tricky?

release to marketplace is always time costly, we need to wait for a while.

**Comment by MISSPIKLA** [comment]
> sorry but I cannot get your point. which part is tricky?
> 
> release to marketplace is always time costly, we need to wait for a while.

The question was addressed to @VinodAnandan regarding his statement on the release to SonarQube marketplace for last Saturday. Anyways, we've replaced the jar file with the version uploaded to Maven Central, thank you.

**Comment by VinodAnandan** [comment]
@MISSPIKLA apologies for the late reply. for the SonarQube marketplace release, we have to meet the requirements from SonarSource ( https://docs.sonarqube.org/display/DEV/Deploying+to+the+Marketplace ). We have noticed a compatibility issue ( https://github.com/spotbugs/sonar-findbugs/issues/226 ) prior to the request for the feedback submission.  That's the main reason I didn't submit the RFF to the SQ community as it may necessarily provide a good impression. . Feel free to submit pull request to resolve the compatibility issue.

**Comment by VinodAnandan** [comment]
Also, if you would support sonar-findbugs 3.9 RFF only with SonarQube 6.7 LTS >= SonarQube 7.3, please let us know ( https://github.com/spotbugs/sonar-findbugs/issues/228 ). We can also submit the RFF with limited compatibility.

**Pull request merged**
