### PR TITLE
Upgrade SpotBugs to 4.8.5

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by hazendaz** [comment]
@gtoison Got trigger happy and merged renovate PR for this, applied the rest as seen on last time you updated for this PR.

**Comment by gtoison** [comment]
Did you run the groovy script to update the rules metadata?
It might be that the files remained the same but I use to run it when upgrading spotbugs (or the plugins)

**Comment by hazendaz** [comment]
> Did you run the groovy script to update the rules metadata? It might be that the files remained the same but I use to run it when upgrading spotbugs (or the plugins)

I did not, just followed the general last commit for this.

**Comment by gtoison** [comment]
There's a procedure to update the rules metadata here: https://github.com/spotbugs/sonar-findbugs/blob/master/generate_profiles/README.md
It's quite possible that running the script does not update the files.
The typical cases when it's needed are when there's a new detector, or when some messages where updated; but it's a good habit to run it when there's a new version

**Comment by hazendaz** [comment]
> There's a procedure to update the rules metadata here: https://github.com/spotbugs/sonar-findbugs/blob/master/generate_profiles/README.md It's quite possible that running the script does not update the files. The typical cases when it's needed are when there's a new detector, or when some messages where updated; but it's a good habit to run it when there's a new version

Ran the script, no changes made.

**Comment by gtoison** [comment]
Thank you!

**Pull request merged**
